apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: drontpipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: drontpipelinesjavascriptdocker 
    spec:
      containers:
        - name: drontpipelinesjavascriptdocker 
          image: fairtstreg.azurecr.io/drontpipelinesjavascriptdocker
          ports:
          - containerPort: 8080